name: Release
env:
  MACOSX_DEPLOYMENT_TARGET: '10.14'
on:
  release:
    types: [published]
jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Compile
        run: |
           & ".\build.bat"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sus-windows
          path: |
            sus.exe
            libtcc1.a
            libtcc.dll
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          chmod +x ./build
          ./build
          sudo mv /usr/local/lib/tcc/libtcc1.a .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sus-linux
          path: |
            sus
            libtcc1.a
  publish:
    needs:
      - build-windows
      - build-linux
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Zipping all artifacts
        run: |
          cd artifacts
          for i in */; do zip -0 -r "${i%/}.zip" "$i" & done; wait
          mv *.zip ..
      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sus-windows.zip
          asset_name: sus-windows.zip
          asset_content_type: application/zip
      - name: Upload Linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./sus-linux.zip
          asset_name: sus-linux.zip
          asset_content_type: application/zip
