name: Test
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - .editorconfig
  pull_request: null
jobs:
  windows-mingw:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    name: MinGW GCC
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Building dependencies and compiling
      run: |
        npm i fast-fail
        & ".\build.bat" gcc
    - name: Testing sussy executable
      run: |
        node .\test.mjs
  windows-msvc:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    name: Microsoft Visual C++ (MSVC)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Building dependencies and compiling
      run: |
        npm i fast-fail
        & ".\build.bat"
    - name: Testing sussy executable
      run: |
        node .\test.mjs
  windows-clang:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    name: Windows Clang
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Building dependencies and compiling
      run: | 
        npm i fast-fail
        & ".\build.bat" clang
    - name: Testing sussy executable
      run: |
        node .\test.mjs
  linux-gcc:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    name: Linux GCC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Building dependencies and compiling
      run: |
        npm i fast-fail
        chmod +x ./build
        ./build
    - name: Testing sussy executable
      run: |
        node ./test.mjs
  linux-clang:
    if: '!contains(github.event.head_commit.message, ''skip ci'')'
    name: Linux Clang
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: egor-tensin/setup-clang@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Building dependencies and compiling
      run: |
        npm i fast-fail
        chmod +x ./build
        ./build clang
    - name: Testing sussy executable
      run: |
        node ./test.mjs