name: prettier
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - 'src/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Prettier rust code!
        run: cargo fmt
      - name: Prettier C source files!
        run: clang-format -i src/hooks/*.c
      - name: Prettier C header files!
        run: clang-format -i src/hooks/*.h
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore: prettier'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}